clean : 
	rm -f *.log *.idx *.cxx *.cfg *.aux *.synctex.gz *.mp *.giac *.gnuplot *.dvi *.maf *.mtc *.mtc0 *.out *.tex.bak *.toc *.table

clean_all : clean
	rm -f *pdf 

clean_Trash :
	rm /Volumes/SOURCE/.Trashes
