#	"/Library/TeX/texbin/pdflatex" -synctex=1 -interaction=nonstopmode --shell-escape *.tex
clean  : 
	rm -f *log *aux *synctex.gz *toc *mp *bak *cxx *idx *gnuplot *table *cfg  *maf *mtc *mtc0  *giac
clean_all: clean 
	rm -f *pdf 
